dist: xenial
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        - GCOV_SCRIPT="bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-8"
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
            - g++-8 # Install g++ stdlibc++
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - GCOV_SCRIPT="echo "GCov not available for clang"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_CODE_COVERAGE=TRUE
  - cmake --build . -- -j2 
  - ctest
  - eval "${GCOV_SCRIPT}"