dist: bionic
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10 && BUILD_TYPE=Release"
        
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CC=gcc-10 && CXX=g++-10 && BUILD_TYPE=Debug"
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - g++-10 # Install g++ for stdlibc++
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10 && BUILD_TYPE=Release"
    
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-10
          packages:
            - clang-10
            - g++-10 # Install g++ for stdlibc++
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++10 && BUILD_TYPE=Debug"

install:
    - pip install --user conan
    - conan user
    - conan --version

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build . -- -j2 
  - ctest --output-on-failure