platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2017

clone_folder: c:/dla/

before_build:
- ps: >-
    if ($env:PLATFORM -eq "x86") {
        $env:generator="Visual Studio 15 2017"
    }
    else {
        $env:generator="Visual Studio 15 2017 Win64"
    }
    
    pip install --user conan

    mkdir build
    
    cd build
    
    cmake c:/dla/ -G $env:generator

build_script:
- cmake --build . --config %CONFIGURATION%

test_script:
- ctest -C %CONFIGURATION%
