platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

image:
  - Visual Studio 2017

clone_folder: c:/dla/

before_build:
- ps: >-
    if ($ENV:PLATFORM -eq "x86") {
        $ENV:GENERATOR="Visual Studio 15 2017"
    }
    else {
        $ENV:GENERATOR="Visual Studio 15 2017 Win64"
    }
    
    $ENV:PATH="$ENV:PATH;C:\Users\appveyor\AppData\Roaming\Python\Scripts"
    
    pip install --user conan

    mkdir build
    
    cd build
    
    cmake c:/dla/ -G $ENV:GENERATOR

build_script:
- cmake --build . --config %CONFIGURATION%

test_script:
- ctest -C %CONFIGURATION%
