name: Github Actions CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, ubuntu-latest]
        build_type: [Debug, Release]
        include: 
        - os: macos-latest
          name: "MacOS clang"
          c_compiler: clang
          cxx_compiler: clang++
        - os: ubuntu-latest
          name: "Ubuntu clang"
          c_compiler: clang-9
          cxx_compiler: clang++-9
        - os: ubuntu-latest 
          name: "Ubuntu gcc"
          c_compiler: gcc-9
          cxx_compiler: g++-9

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1.2.0
    - uses: lukka/get-cmake@v3.17.1
    - uses: seanmiddleditch/gha-setup-ninja@v1

    - name: Prepare
      run: |
        python -m pip install --upgrade pip
        pip install conan

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=${{matrix.c_compiler}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} -DDLA_BUILD_TESTS=ON

    - name: Build
      run: |
        cd build
        cmake --build .

    - name: Test
      run: |
        cd build
        ctest . --output-on-failure
