name: Github Actions CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1.2.0
    - uses: lukka/get-cmake@v3.17.1
    - uses: seanmiddleditch/gha-setup-ninja@v1

    - name: Prepare
      run: |
        python -m pip install --upgrade pip
        pip install conan

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DDLA_BUILD_TESTS=ON

    - name: Build
      run: |
        cmake --build .

    - name: Test
      run: |
        ctest . --output-on-failure
