name: Github Actions CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.name }} ${{ matrix.compiler }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        compiler: [gcc, clang]
        build_type: [Debug, Release]
        include: 
        - compiler: gcc
          c_compiler: gcc-9
          cxx_compiler: g++-9
          gen_metrics: OFF
        - compiler: clang
          c_compiler: clang
          cxx_compiler: clang++
          gen_metrics: ON
        - os: macos-latest
          name: MacOS
        - os: ubuntu-latest
          name: Ubuntu

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1.2.0
    - uses: lukka/get-cmake@v3.17.1
    - uses: seanmiddleditch/gha-setup-ninja@v1

    - name: Prepare
      run: |
        python -m pip install --upgrade pip
        pip install conan

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -GNinja -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_C_COMPILER=${{matrix.c_compiler}} -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} -DDLA_GENERATE_METRICS=${{matrix.gen_metrics}} -DDLA_BUILD_TESTS=ON

    - name: Build
      run: |
        cd build
        cmake --build .
        
    - name: Metrics Artifact
      if: matrix.compiler == 'clang'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }} ${{ matrix.compiler }} ${{ matrix.build_type }} Metrics
        path: build/metrics.json

    - name: Test
      run: |
        cd build
        ctest . --output-on-failure
